### 사용자 등록

POST localhost:3333/members/register
Content-Type: application/json

{
  "memberId": "123",
  "password": "12",
  "email": "email",
  "name": "member"
}

### 사용자 조회
GET localhost:3333/members/1


### 로그인
POST localhost:3333/login
Content-Type: application/json

{
  "memberId": "123",
  "password": "12"
}

### member-projects 추가
POST localhost:3333/member-projects
Content-Type: application/json

{
  "memberId": "123",
  "projectId": 3
}

### member-projects 제거
DELETE localhost:3333/member-projects
Content-Type: application/json

{
  "memberId": "123",
  "projectId": 3
}

### member-projects 조회
GET localhost:3333/member-projects/123